version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    volumes:
      - ./database:/var/lib/mysql
      - ./docker/init-database.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -p$MYSQL_ROOT_PASSWORD mysql -e 'select 1;'"
      interval: 1s
      retries: 120
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./docker/php
    # этот образ будет общаться с mysql
    links:
      - db
    volumes:
      - ./backend:/var/www
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./backend:/var/www
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    links:
      - php
